### ISSUE TITLE
🐛 Saving models to file seems to be broken

### ISSUE THREAD

**Issue by heikomat** [process-engine/process_repository#5]
#### Describe your issue

When a model is loaded from a local file from disk, then updated, the repository should write the changes back to the original file. This seems to be broken. Because the local file is used to overwrite existing models with the same name on process-engine-start, this results in some models that can never be changed.

When changing a model that has a local-file-counterpart, the change is written to the database, but not to the file. When the process-engine is then restartet, it will see the local file and will "update" the model in the database, therefore reverting the changes

#### How can others reproduce the issue?

- update a process-model that has a local-file-counterpart setup
- restart the process-engine
- see how your changes are gone

#### Possible solution

When a process is updated, the local-file-counterpart has to be updated. This is implemented, but seems to simply be broken.

#### What's your setup

- OS (`Windows/OS X/Linux` + `version`): OSX
- Node (`node --version`): 7.10.1
- NPM (`npm --version`): 4.2.0

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by heikomat** [comment]
@ppoetschke 
Before calling updateBpmn, charon makes sure that the process is flagged as draft, because otherwise updateBpmn throws the error `'Process definition is not a draft!'`.

after the updateBpmn-call, if it was not flagged as draft before, charon removes the draft-flag again.

i would've expected, thate updateBpmn saves back to the file if there is one, but `processRepository.saveProcess` is only ever called in `publishDraft`, not in `updateBpmn`.

According to your input i'd assume, that in order to update a process, you'd have to:
- flag the process-model as draft
- apply the changes to the model
- call `updateBpmn` with the changed draft (which saves to the DB only)
- call `publishDraft` on the process-model (which saves to the DB again, but also saves to the disk)

is that correct?

Being a draft assumes, that there is a non-draft model. you can't however flag something as draft without abusing the datastore. The only way something can be a draft without using the datastore is, if an entirely new process is created. This is very confusing

\\cc: @cmg-dev @5ebastianMeier @moellenbeck

**Comment by ppoetschke** [comment]
@heikomat It's all handled by the methods getDraft, getLatest and publishDraft of ProcessDef. There is no need to change the flags manually. I considered the way Charon handles this always as workaround, not as final implementation of this versioning story.

**Comment by heikomat** [comment]
@ppoetschke it **is** a workaround, but only because versioning isn't finalized

**Comment by ppoetschke** [comment]
@heikomat The current implementation of versioning in the process engine itself **is** finalized in a first simple iteration in the scope of the first milestone of the contract with Huf. This is why it's merged and published.
The implementation in Charon **is not** yet finalized as it's not taking into account the intended workflow.
I'm very against changing the behavior of the process engine in this iteration as this would break the function of existing deployments and would not be in the scope of stabilization the process engine. I would appreciate to improve versioning later on aligned by a good product strategy.

**Comment by cmg-dev** [comment]
@ppoetschke @heikomat: I will have look into this matter tomorrow.

But please feel free so answer those questions:

If my understanding ist correct, the `ProcessDef` provides - along others - the following methods:

1. `getDraft()`
1. `getLatest()`
1. `publishDraft()`

**Q1:** Why isn't Charon using those methods?
**Q2:** If Charon will use them, will this solve the issue?
**Q3:** Do we need to update the APIs to enable Charon to use those?
**Q4:** Who else is using those methods?

If I recall correctly, there has been quite a rush with implementing the versioning.

**Q5:**  Maybe we should put it on the Roadmap for later refactoring? 

@ppoetschke: It may very well be, that the "Versioning" is in line with HSMs requirements.
But I do not really believe, that calling something DRAFT, introduces a proper "Versioning".

**Q6:** Do you agree on this?
I don't want to discuss, but you folks are ahead of me, in your understanding, I'm trying to catch up ;)

Speaking of:

> (...) The current implementation of versioning in the process engine itself is finalized in a **first simple iteration**(...)

leads me to

**Q7:** When are the further steps planned?

I'm sure there are documents about this.

@ppoetschke:
Never the less: I agree, that fixes in Charon, should fix things, rather then break. If my understanding matches your concerns at this point.

@heikomat: 
Generally I like your approach. We will surely see it/parts of it in the next iterations.

**Comment by ppoetschke** [comment]
@cmg-dev Q1: Lack of documentation. It was communicated to inspect the old client api, where usage is demonstrated.
Q2: Yes.
Q3: Which APIs? Calling these methods is already part of datastore API.
Q4: MCP from Huf and Vorstart. All projects based on the React frontend use it already.
Q5: Definitively, but I wouldn't call it refactoring but further development.
Q6: As I said, it's a simple first iteration mainly driven by budget. For "proper" versioning we have more complex requirements. So, yes I agree on this.
Q7: As you know we are working on a roadmap for product development. We will see how this will fit in the product strategy.

Generally I think it's correct to tightly bind the model to the process instance (thats one requirement of versioning). But I still do not think it's good for performance reasons to copy the whole model to every instance. We want to be able to execute several thousands of processes per second!

**Comment by heikomat** [comment]
i thought about another solution, which encompasses saving a new version of a model, every time something in the model changed. This would result in no instance ever referencing a non-existing model.

With this we'd never be able to delete any version of a model, that was ever referenced by a process-instance. This is however not a problem if we just introduce a deleted-timestamp for the models.

Another thing to consider with this: the draft-flag/draft-process. who has what exact requirements regarding the draft-process? Maybe using this idea could make the draft-flag obsolete. **If not:** why not. **What are the requirements?**

\\cc: @5ebastianMeier @cmg-dev @ppoetschke

**Comment by 5ebastianMeier** [comment]
With the new proposal from @heikomat we could introduce a `deleted` flag on the model (and maybe for other items later on).

I think we need to make sure that every process instance is referencing an existing model (deleted or not).

We could still allow versions of the model in the version history that are not referenced by any process instance (mainly for archival purposes)

**Comment by heikomat** [comment]
@5ebastianMeier i moved my comment because we are mixing up two issues here: This one is about the savong of the model to disk, what you are talking about is that things are referenced wrongly if process-models are deleted, which is this issue: https://github.com/process-engine/charon/issues/52
